apiVersion: ENC[AES256_GCM,data:jEk=,iv:BlFZuLXABGbEbZuAXgNuC+CcrL1NcXML+W59EZ0PSH0=,tag:88yflCG7qsLAnGBe/lXLCw==,type:str]
data:
    client-id: ENC[AES256_GCM,data:6zLmy/RPLDzb5y5JbOab06I5ZBAuGDsTgDHMQQ==,iv:V9yV4XP6LcycHkyxI5roILS8OY5g9PFRodR3yQ3UYe4=,tag:PF0b03CW+UyoiCokdzyD+A==,type:str]
    client-secret: ENC[AES256_GCM,data:R+LRDrkpBuef9GpSohbOxahAhiXsHIvk46eRON1DbMcj2gSCIhMPFFnmX+3kteZtD4JI+JAKO1E=,iv:dKw2Pw+eb1Wprkx33hVHUEyRxXbNXRL6/IXarIrFUSQ=,tag:IDgZAAJy1ZPb6SWIddO5kQ==,type:str]
kind: ENC[AES256_GCM,data:Nyn8UBzR,iv:3a5NkaJQIvbEwxHzzsH4J+OT07MlPAVC2UCJKNQynbs=,tag:E4Qjz6VPMWepMtzK2/MDOQ==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:mcBx2PbwGRfch4I/VA==,iv:99+ZssTOZ26JA+3F2WRdC5kY3nMeFCaeloQiZX5V+XU=,tag:k6g62+A62+jWh8IcF3KxfA==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/hobby-274617/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2021-10-04T20:48:03Z'
        enc: CiQAv9Qb/9/YGtQYPhF17k8+d6yNKUEFcER1vFherxxZw10sRHYSSQBHB6yLFVIT2AMJ8QZh/ae3I074PX+YXVlr8KSgJ2xPvTd7XRJ44PyfcPMf/y3Dg/8jNf9PBi1aULLj7ayi+QyvojAtLn5THw0=
    azure_kv: []
    lastmodified: '2021-10-04T20:48:04Z'
    mac: ENC[AES256_GCM,data:qOPvcSWCxLYJr/iMcvG+EBmCoadF3V28hWYN8BDG6OmlPCdjgp6vCZjdX1F1ysanADY1i0UhldpdIeNcGnrdSePTLzGggazNha+M47LJE6xGJJT3mCJ4hr7pmt0MQU8fdS85mA9P8I0RIBZ/XPaC2cnt4HtiwnCgaNI8/HLc4rE=,iv:0f+riU7zxyiHoMe+qVv+jo7b15KXQ7M+xe2NbzSrMcU=,tag:P+EUYGl9OmYLUBAQ4To0gA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.4.0
