apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dex
  namespace: dex
spec:
  gateways:
    - istio-system/dev-gateway
  hosts:
    - 'login.bychkowski.dev'
  http:
    - route:
        - destination:
            host: dex.dex.svc.cluster.local
            port:
              number: 5556
      match:
      - uri:
          prefix: /oauth2   