apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-ui
  namespace: argocd
spec:
  gateways:
    - istio-system/platform-gateway
  hosts:
    - 'auth.bychkow.ski'
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: dex.dex.svc.cluster.local
            port:
              number: 5556
