apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  ## Common
  # - _argocd-applications/argocd.yaml
  # - _argocd-applications/istio-system.yaml
  # - _argocd-applications/cert-manager.yaml
  # - _argocd-applications/dex-auth.yaml

  - _argocd-applications/testapp.yaml

  # - _argocd-applications/platform.yaml
  
