apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  ## Common
  - argocd-applications/argocd.yaml
  - argocd-applications/testapp.yaml
  - argocd-applications/istio-system.yaml
# - argocd-applications/istio-operator.yaml
# - argocd-applications/istio.yaml
# - argocd-applications/istio-resources.yaml
