apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/istio/istio.git
    targetRevision: '1.11.0'
    path: manifests/charts/base
    helm:
      valuesFile: values.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
