apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-control
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/istio/istio.git
    targetRevision: '1.11.0'
    path: manifests/charts/istio-control/istio-discovery
    helm:
      valueFiles: 
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
