apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  ## Common
- ../../base/
- virtualservice.yaml
## Only on initial deployment of argocd
# - env/secret-gcp-kms.yaml
