apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:mbychkowski/my-deployment.git
    targetRevision: demo/gitops-001
    path: distribution/testapp/base
    kustomize:
      version: v4.2.0_ksops.v2.6.0
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
