apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: platform-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
    app: istio-ingressgateway
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
    hosts:
    - '*.bychkow.ski'      
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: https
    tls:
      mode: SIMPLE
      credentialName: bychkow-ski-ingress-cert-tls # This should match the Certificate secretName
    hosts:
    - '*.bychkow.ski' # This should match a DNS name in the Certificate      
