apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress-my-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/istio/istio.git
    targetRevision: '1.11.0'
    path: manifests/charts/gateways/istio-ingress
    helm:
      valueFiles: 
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: my-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
