apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx
  namespace: test
spec:
  gateways:
    - istio-system/platform-gateway
  hosts:
    - 'bychkow.ski'
  http:
  - match:
    - uri:
        prefix: /
    route:
      - destination:
          host: nginx
          port:
            number: 80
